source: site/
url: "https://undernet.io"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: A modular, configuration-first front-end framework. No strings.
      description: Use powerful Sass, CSS, and JavaScript tools to enable better development and user experience.
  - scope:
      path: docs
    values:
      layout: docs

package:
  version: 7.0.2
  cdn_integrity_css: sha256-8AIkNdWWsuSg3sleT26Ed39Kc8GhdXXX0REEdWWxXyI=
  cdn_integrity_js: sha256-CNNIcn/3mz6tA/3wq12uqGJ44sOdZoaKaPrWwcyJ5nI=
