baseurl: "/undernet"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-gzip

gzip:
  extensions:
    - ".html"
    - ".css"
    - ".js"

exclude:
  - README.md
  - package.json
  - package-lock.json
  - postcss.config.js
  - rollup.config.js
  - rollup.config.site.js
  - babel.config.js
  - jest.config.js
  - src/
  - dist/
  - bin/
  - lib/
