defaults:
  - scope:
      path: assets/img
    values:
      image: true

exclude:
  - babel.config.js
  - jest.config.js
  - package-lock.json
  - postcss.config.js
  - rollup.config.js
  - src
  - dist
  - bin

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-autoprefixer

# this echoes .browserslistrc
autoprefixer:
  only_production: true
  browsers:
    - last major version
    - ie 11
    - edge >= 15
    - firefox >= 54
    - chrome >= 51
    - safari >= 10
    - ios >= 9
    - opera >= 38

baseurl: "/undernet"
