source: site/
url: "https://undernet.io"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: A modular, configuration-first front-end framework. No strings.
      description: Use powerful Sass, CSS, and JavaScript tools to enable better development and user experience.
  - scope:
      path: docs
    values:
      layout: docs

package:
  version: 8.1.0
  cdn_integrity_css: sha256-t10LWO9nOSH/ZebcqTaWStw4Klck34xxlccrhVaomxg=
  cdn_integrity_js: sha256-am6vAHMcM/VM5t7fA2/WTBPL4UbehfbYc4M7aLFe824=
