sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
plugins:
  - jekyll-gzip
  - jekyll-autoprefixer
gzip:
  extensions:
    - ".html"
    - ".css"
    - ".js"
autoprefixer:
  # This should match .browserslistrc
  browsers:
    - Chrome >= 69
    - Firefox >= 54
    - iOS >= 12.2
    - Opera >= 56
    - Safari >= 12.1
    - not Explorer > 0
    - not Edge > 0
