baseurl: "/undernet"

sass:
  sass_dir: _sass
  style: compressed

exclude:
  # jekyll stuff
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # undernet stuff
  - package.json
  - package-lock.json
  - postcss.config.js
  - rollup.config.js
  - rollup.config.site.js
  - babel.config.js
  - jest.config.js
  - src/
  - dist/
  - bin/
  - lib/
