version: 2

jobs:
  build:
    working_directory: ~/undernet
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/undernet

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    working_directory: ~/undernet
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run lint
      - run: npm test

  deploy-staging:
    working_directory: ~/undernet
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "38:69:6d:27:55:79:cb:de:fe:3d:b1:ca:45:b6:73:74"
      - run: gem install bundler:2.1.2
      - run: bundle install
      - run: npm run js:build
      - run: npm run build
      - run:
          name: Deploy to Github
          command: bash .circleci/deploy-staging.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-staging:
          requires:
            - build
            - test
          filters:
            branches:
              ignore:
                - master
